'use server'

import { createClient } from '@/lib/supabase/server'
import { getCurrentUser } from '@/lib/data'
import {
  validateSupportRequest,
  toSupportRequestPayload,
  type SupportRequestErrors,
  type SupportRequestInput,
} from '@/lib/validation/supportRequest'

export type SupportRequestResult =
  | { ok: true; reference: string }
  | { ok: false; message?: string; errors?: SupportRequestErrors }

/** Postgres check_violation — a CHECK constraint in migration 0006 rejected it. */
const CHECK_VIOLATION = '23514'
/** Postgres insufficient_privilege — an RLS policy refused the insert. */
const RLS_VIOLATION = '42501'

/**
 * File a support request.
 *
 * Every field the caller sends is re-validated here even though the form
 * already did it, because the form is a convenience and this is the control.
 * `store_id` and `raised_by` are taken from the session and never from the
 * payload: a crafted request must not be able to file a ticket into another
 * store or attribute one to somebody else.
 *
 * There is no revalidatePath — nothing on /help renders the list of requests,
 * so busting the cache would cost a re-render and buy nothing.
 */
export async function submitSupportRequest(
  input: SupportRequestInput,
): Promise<SupportRequestResult> {
  const { profile, store } = await getCurrentUser()

  // No role check: every signed-in member of a store may ask for help. That is
  // deliberate — staff are the people most likely to hit something confusing,
  // and a support form they cannot reach is the same as no support form.

  const errors = validateSupportRequest(input)
  if (Object.keys(errors).length > 0) {
    return { ok: false, errors, message: 'Please correct the highlighted fields.' }
  }

  const supabase = await createClient()
  const payload = toSupportRequestPayload(input)

  // `reference` is generated by the database, so it must be selected back
  // rather than computed here — the ticket id shown to the user is then the
  // one actually stored, not a guess that could drift from it.
  const { data, error } = await supabase
    .from('support_requests')
    .insert({ ...payload, store_id: store.id, raised_by: profile.id })
    .select('reference')
    .single()

  if (error) {
    // Each of these is a different thing going wrong and deserves a different
    // sentence. A single "something went wrong" is what makes an app feel
    // broken rather than merely unlucky.
    if (error.code === CHECK_VIOLATION) {
      return {
        ok: false,
        message: 'Some of those details were rejected. Check the message length and try again.',
      }
    }
    if (error.code === RLS_VIOLATION) {
      return {
        ok: false,
        message: 'Your account is not attached to a store, so this could not be filed.',
      }
    }
    return { ok: false, message: `Could not send your request: ${error.message}` }
  }

  // Defensive: `.single()` on a successful insert always returns the row, but a
  // null here would otherwise render "Ticket undefined" at the user.
  if (!data?.reference) {
    return {
      ok: false,
      message: 'Your request was saved, but we could not read back its ticket number.',
    }
  }

  return { ok: true, reference: data.reference }
}
