export interface PdfTable {
  title: string
  head: string[]
  rows: (string | number)[][]
  /** Column indexes to right-align (numbers and money). */
  numericColumns?: number[]
}

export interface PdfReport {
  title: string
  subtitle: string
  kpis: { label: string; value: string }[]
  tables: PdfTable[]
  filename: string
}

/** jspdf-autotable hangs the cursor off the document after each table. */
interface AutoTableCursor {
  lastAutoTable?: { finalY: number }
}

const MARGIN = 40

/**
 * Renders a report to PDF and saves it.
 *
 * jspdf and jspdf-autotable are imported dynamically: together they are the
 * heaviest thing in this app, and nobody who never opens Reports should pay
 * for them in the initial bundle.
 */
export async function exportReportPdf(report: PdfReport): Promise<void> {
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ])

  const doc = new jsPDF({ unit: 'pt', format: 'a4', orientation: 'portrait' })
  const cursor = doc as unknown as AutoTableCursor
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text(report.title, MARGIN, 56)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(110)
  doc.text(report.subtitle, MARGIN, 74)
  doc.setTextColor(0)

  let y = 96

  if (report.kpis.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [report.kpis.map((k) => k.label)],
      body: [report.kpis.map((k) => k.value)],
      theme: 'grid',
      styles: { fontSize: 10, cellPadding: 8 },
      headStyles: { fillColor: [24, 24, 27], textColor: 255, fontStyle: 'bold' },
      bodyStyles: { fontStyle: 'bold', fontSize: 12 },
      margin: { left: MARGIN, right: MARGIN },
    })
    y = (cursor.lastAutoTable?.finalY ?? y) + 28
  }

  for (const table of report.tables) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.text(table.title, MARGIN, y)
    y += 10

    const columnStyles: Record<number, { halign: 'right' }> = {}
    for (const i of table.numericColumns ?? []) columnStyles[i] = { halign: 'right' }

    autoTable(doc, {
      startY: y,
      head: [table.head],
      // An empty section still prints, with a row saying so — a silently
      // missing section reads as "no such report", not "no data".
      body: table.rows.length > 0 ? table.rows : [['No data in this range']],
      theme: 'striped',
      styles: { fontSize: 9, cellPadding: 6, overflow: 'linebreak' },
      headStyles: { fillColor: [244, 242, 238], textColor: 40, fontStyle: 'bold' },
      columnStyles: table.rows.length > 0 ? columnStyles : {},
      margin: { left: MARGIN, right: MARGIN },
    })
    y = (cursor.lastAutoTable?.finalY ?? y) + 28
  }

  // Page numbers last, once the total is known.
  const pages = doc.getNumberOfPages()
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(140)
    doc.text(`Page ${p} of ${pages}`, pageWidth - MARGIN, pageHeight - 24, { align: 'right' })
    doc.text('Generated by StockPulse', MARGIN, pageHeight - 24)
  }

  doc.save(report.filename)
}
